---
- name: Install Nginx Server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: Make sure Nginx service is running
      systemd:
        name: nginx
        state: started
